MySQL:
  enabled: false
  host: localhost
  database: db
  username: user
  password: pass
  port: 3306

Settings:
  save-interval: 600 # em segundos
  commands:
    ranks:
      command: ranks
      aliases: [rank]
    rankup:
      command: rankup
      aliases: [ru, evoluir]

Messages:
  no-requirements: '&6&lVoltz&f&lMC &8&l➜ &cVocê precisa usar um item de evoluir rank para atingir esse rank!'
  last-rank: '&cVocê já está no último rank!'
  insufficient-requirements:
    - '&cVocê não possui todos requisitos para evoluir!'
    - '&cRequisitos:'
    - ''
    - '{requirements}'
    - ''

Titles:
  rankup:
    title: '&6&lUP!'
    subtitle: '&7Você evoluiu de rank!'

Requirements:
  VAULT:
    1: ' &8▶ &e{has}&8/&e{need} ⛃ &8→ &a{progress}%' # lore mostrada no próximo rank/no menu de RankUP/mensagem dos requisitos
    2: ' &8▶ &e{need} ⛃ &8→ &a100%' # lore mostrada nos ranks desbloqueados ou distantes
  EXP:
    1: ' &8▶ &6{has}&8/&6{need} ⏦ &8→ &a{progress}%'
    2: ' &8▶ &6{need} ⏦ &8→ &a100%'

Next-Page:
  type: ARROW
  name: '&aPróxima Página'

Previous-Page:
  type: ARROW
  name: '&cPágina Anterior'

Rankup-Item:
  type: PLAYER_HEAD
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTJjY2I4NGY5YzBjYmIyZWI3YjlhYmJiN2E0ZmM3YjMxODYxNTBkNWU3ZGIwMTg1MmFjNmQ0OTVkZTE3ZTgxMiJ9fX0=
  name: '&5Evoluir Rank &7(Botão direito)'
  lore:
    - '&7Use esse item para evoluir'
    - '&7de rank sem custo!'

Ranks:
  Slave:
    tag: '&8[Escravo]'
    requirements: []
    rankup-commands: []
  Peasant:
    tag: '&a[Camponês]'
    requirements:
      - 'VAULT,10B'
      - 'TOKENS,10k'
    rankup-commands:
      - 'pex user {player} group remove {old_rank}'
      - 'pex user {player} group add {new_rank}'

Number-Formatter:
  - "k"
  - "M"
  - "B"
  - "T"
  - "Q"
  - "QQ"
  - "S"
  - "SS"
  - "O"
  - "N"
  - "D"